### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by mracos** [mracos/pptrecorder#1]
- [ ] thread the code that grab the image and the onde that builds the ppt
- [ ] resize the image to (or position as a background)
- [ ] log things as (the pyscreenshot) background
- [ ] write more tests
- [ ] use pipfile
- [ ] implement a little repl / gui to stop recording
